# Generated by Django 6.0.4 on 2026-04-10 17:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=120)),
                ('company', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('help_topic', models.CharField(choices=[('ai_automation', 'AI and Intelligent Automation'), ('cloud_infrastructure', 'Cloud, Infrastructure and Platform Engineering'), ('cybersecurity', 'Cybersecurity, Backup and Business Continuity'), ('modern_workplace', 'Modern Workplace and Business Applications'), ('networking', 'Networking, Devices and Physical Infrastructure'), ('strategy_call', 'General Strategy Call'), ('other', 'Other')], default='strategy_call', max_length=30)),
                ('contact_method', models.CharField(choices=[('email', 'Email'), ('phone', 'Phone'), ('either', 'Either')], default='either', max_length=10)),
                ('message', models.TextField()),
                ('submitted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_read', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Enquiry',
                'verbose_name_plural': 'Enquiries',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='InsightPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('category', models.CharField(choices=[('AI & Automation', 'AI & Automation'), ('Cloud & Infrastructure', 'Cloud & Infrastructure'), ('Cybersecurity', 'Cybersecurity'), ('Modern Workplace', 'Modern Workplace'), ('Strategy', 'Strategy')], max_length=30)),
                ('excerpt', models.CharField(max_length=300)),
                ('body', models.TextField()),
                ('published', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-published_at'],
            },
        ),
    ]
